#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.cad67e4.name = "Upgrade from 1.9.2~ynh2"
    test_upgrade_from.6c353b7492e26e4e859726b8a203c935a5a308eb.name = "Upgrade from 2.3.0~ynh1"
